require("dotenv").config();

module.exports = {
  port: Number(process.env.PORT) || 4000,
  clientOrigin:
    process.env.CLIENT_ORIGIN ||
    "http://localhost:3000,http://localhost:3001,http://localhost:3002",
  mongodbUri: process.env.MONGODB_URI || "mongodb://localhost:27017/arsenal_union",
  adminPhone: process.env.ADMIN_PHONE || "+998901111111",
  adminPassword: process.env.ADMIN_PASSWORD || "admin1234",
  adminEmail: process.env.ADMIN_EMAIL || "admin@arsenal.union",
  adminFirstName: process.env.ADMIN_FIRST_NAME || "Admin",
  adminLastName: process.env.ADMIN_LAST_NAME || "Union",
  adminName:
    process.env.ADMIN_NAME ||
    `${process.env.ADMIN_FIRST_NAME || "Admin"} ${process.env.ADMIN_LAST_NAME || "Union"}`.trim(),
  adminSecretKey: process.env.ADMIN_SECRET_KEY || "arsenal-admin-secret",
  agentSecret: process.env.AGENT_SECRET || "arsenal-agent-dev-secret",
  billingProvider: process.env.BILLING_PROVIDER || "custom",
  ggleapApiUrl: process.env.GGLEAP_API_URL || "",
  ggleapApiKey: process.env.GGLEAP_API_KEY || "",
  ccbootApiUrl: process.env.CCBOOT_API_URL || "",
  ccbootApiKey: process.env.CCBOOT_API_KEY || "",
  publicSiteUrl: process.env.PUBLIC_SITE_URL || process.env.CLIENT_ORIGIN || "http://localhost:3000",
  telegramBotToken: process.env.TELEGRAM_BOT_TOKEN || "",
  telegramBotUsername: process.env.TELEGRAM_BOT_USERNAME || "arsenalGC_bot",
  telegramAdminBotToken: process.env.TELEGRAM_ADMIN_BOT_TOKEN || "",
  telegramAdminBotUsername: process.env.TELEGRAM_ADMIN_BOT_USERNAME || "arsenal_union_bot",
  telegramAdminChatId: process.env.TELEGRAM_ADMIN_CHAT_ID || "",
  paymentMode: process.env.PAYMENT_MODE || "live",
  publicApiUrl: process.env.PUBLIC_API_URL || `http://127.0.0.1:${Number(process.env.PORT) || 4000}`,
  paymeMerchantId: process.env.PAYME_MERCHANT_ID || "",
  paymeKey: process.env.PAYME_KEY || "",
  paymeApiUrl: process.env.PAYME_API_URL || "https://checkout.paycom.uz/api",
  paymeCheckoutBase: process.env.PAYME_CHECKOUT_BASE || "https://checkout.paycom.uz",
  clickMerchantId: process.env.CLICK_MERCHANT_ID || "",
  clickServiceId: process.env.CLICK_SERVICE_ID || "",
  clickMerchantUserId: process.env.CLICK_MERCHANT_USER_ID || "",
  clickSecretKey: process.env.CLICK_SECRET_KEY || "",
  clickApiUrl: process.env.CLICK_API_URL || "https://api.click.uz/v2",
  clickDefaultPhone: process.env.CLICK_DEFAULT_PHONE || "",
  uzumMerchantId: process.env.UZUM_MERCHANT_ID || "",
  uzumTerminalId: process.env.UZUM_TERMINAL_ID || "",
  uzumSecretKey: process.env.UZUM_SECRET_KEY || "",
  uzumApiUrl: process.env.UZUM_API_URL || "https://api.uzum.uz/api/v1",
};
